module.exports.uploadImage = async (req, newHadith) => {
  if (!req.files.length) {
    newHadith.images.push({
      url: "https://images.unsplash.com/photo-1552423316-be19a6e4e9f9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&q=80",
      filename: "autoGenerated",
    });
  } else {
    newHadith.images = req.files.map((f) => ({
      url: f.path,
      filename: f.filename,
    }));
  }
};
